queue_rules:
  - name: default
    queue_conditions:
      - label=merge
    merge_conditions:
    - and:
      - check-success=Cloudflare Pages

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - and:
      - "#approved-reviews-by>=1"
      - "approved-reviews-by=sonicjhon1"
    actions:
      merge:
        method: merge
